# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]
# Powerlevel10k - 必须放在最前面加载
[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
# 只加载 OMZ 的一些基础库和它自带的插件
use = [
    "lib/completion.zsh",
    "lib.sh",
    "lib/history.zsh",
    "plugins/git/git.plugin.zsh",
    "plugins/fzf/fzf.plugin.zsh"
]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
